enigma:
  key-specification:
    key: "key1234"
    iterations: 65536
    salt: "salt1234"
    iv: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
  encrypt-database: true

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:~/h2databases/enigma-enc;INIT=create schema if not exists enigma;
  liquibase:
    change-log: classpath:/db/changelog-local.xml

server:
  ssl:
    key-alias: enigmaserver
    key-store-password: 2secure4u
    key-store-type: pkcs12
    key-store: classpath:enigmaserver.p12
    trust-store-password: 2secure4u
    trust-store-type: pkcs12
    trust-store: classpath:enigmaserver.p12
    client-auth: need