enigma:
  key-specification:

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:~/h2databases/enigma;INIT=create schema if not exists enigma;
  liquibase:
    change-log: classpath:/db/changelog-local.xml

server:
  ssl:
    key-alias: enigmaserver
    key-store-password: 2secure4u
    key-store-type: pkcs12
    key-store: classpath:enigmaserver.p12
    trust-store-password: 2secure4u
    trust-store-type: pkcs12
    trust-store: classpath:enigmaserver.p12
    client-auth: need