server:
  ssl:
    enabled: true
  servlet:
    context-path: /enigma
  port: 8444
spring:
  application:
    name: Enigma
enigma:
  http-port: 8081
  iterations: 65536
  private-key-length: 512
  salt-length: 256
  encrypt-database: false